"""Tests for WhisperSpeechRecogniser.

Unit tests mock the Whisper model entirely.
The integration test at the bottom uses the real cached audio file produced by
the live TTS script and requires the Whisper model to be available on disk.
"""

import math
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from src.sr.base import SpeechRecogniser, TranscriptResult
from src.sr.whisper_sr import WhisperSpeechRecogniser, _mean_confidence

# ---------------------------------------------------------------------------
# The real audio file generated by scripts/test_tts_live.py
# ---------------------------------------------------------------------------
_AUDIO_CACHE = Path("audio_cache")
_LIVE_AUDIO = _AUDIO_CACHE / "cf006606aa876074.mp3"
_LIVE_TEXT = "For God so loved the world."


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

def _make_segments(*logprobs: float) -> list[dict]:
    """Build minimal Whisper segment dicts with the given avg_logprob values."""
    return [{"avg_logprob": lp} for lp in logprobs]


def _mock_whisper_result(text: str, segments: list[dict]) -> dict:
    """Return a dict shaped like Whisper's transcribe() output."""
    return {"text": text, "segments": segments}


@pytest.fixture
def mock_model() -> MagicMock:
    """A mock Whisper model whose transcribe() is not yet configured."""
    return MagicMock()


@pytest.fixture
def recogniser(mock_model: MagicMock, monkeypatch: pytest.MonkeyPatch) -> WhisperSpeechRecogniser:
    """WhisperSpeechRecogniser with the Whisper model replaced by a mock."""
    monkeypatch.setenv("WHISPER_MODEL", "base")
    with patch("src.sr.whisper_sr.whisper.load_model", return_value=mock_model):
        sr = WhisperSpeechRecogniser()
    return sr


# ---------------------------------------------------------------------------
# _mean_confidence helper
# ---------------------------------------------------------------------------

class TestMeanConfidence:
    def test_no_segments_returns_zero(self) -> None:
        assert _mean_confidence([]) == 0.0

    def test_single_segment_zero_logprob(self) -> None:
        # exp(0) == 1.0
        assert _mean_confidence(_make_segments(0.0)) == pytest.approx(1.0)

    def test_single_segment_negative_logprob(self) -> None:
        lp = -0.5
        assert _mean_confidence(_make_segments(lp)) == pytest.approx(math.exp(lp))

    def test_multiple_segments_averaged(self) -> None:
        lp_a, lp_b = -0.4, -0.8
        expected = math.exp((lp_a + lp_b) / 2)
        assert _mean_confidence(_make_segments(lp_a, lp_b)) == pytest.approx(expected)

    def test_very_negative_logprob_clamped_above_zero(self) -> None:
        # exp(-100) is ~3.7e-44, should still be >= 0
        result = _mean_confidence(_make_segments(-100.0))
        assert 0.0 <= result <= 1.0

    def test_positive_logprob_clamped_to_one(self) -> None:
        # Whisper can sometimes produce slightly positive logprobs; clamp to 1.0
        assert _mean_confidence(_make_segments(0.5)) == pytest.approx(1.0)

    def test_three_segments(self) -> None:
        lps = [-0.2, -0.6, -1.0]
        expected = math.exp(sum(lps) / 3)
        assert _mean_confidence(_make_segments(*lps)) == pytest.approx(expected)


# ---------------------------------------------------------------------------
# Initialisation
# ---------------------------------------------------------------------------

class TestInit:
    def test_uses_whisper_model_env_var(self, monkeypatch: pytest.MonkeyPatch) -> None:
        """WhisperSpeechRecogniser must load the model named in WHISPER_MODEL."""
        monkeypatch.setenv("WHISPER_MODEL", "tiny")
        with patch("src.sr.whisper_sr.whisper.load_model") as mock_load:
            mock_load.return_value = MagicMock()
            WhisperSpeechRecogniser()
        mock_load.assert_called_once_with("tiny")

    def test_defaults_to_base_model(self, monkeypatch: pytest.MonkeyPatch) -> None:
        """When WHISPER_MODEL is not set, the 'base' model must be loaded."""
        monkeypatch.delenv("WHISPER_MODEL", raising=False)
        with patch("src.sr.whisper_sr.whisper.load_model") as mock_load:
            mock_load.return_value = MagicMock()
            WhisperSpeechRecogniser()
        mock_load.assert_called_once_with("base")

    def test_implements_abstract_interface(self, recogniser: WhisperSpeechRecogniser) -> None:
        assert isinstance(recogniser, SpeechRecogniser)


# ---------------------------------------------------------------------------
# File handling
# ---------------------------------------------------------------------------

class TestFileHandling:
    def test_missing_file_raises_file_not_found(
        self, recogniser: WhisperSpeechRecogniser, tmp_path: Path
    ) -> None:
        missing = tmp_path / "nonexistent.mp3"
        with pytest.raises(FileNotFoundError, match="nonexistent.mp3"):
            recogniser.recognise(missing)

    def test_missing_file_does_not_call_model(
        self, recogniser: WhisperSpeechRecogniser, mock_model: MagicMock, tmp_path: Path
    ) -> None:
        with pytest.raises(FileNotFoundError):
            recogniser.recognise(tmp_path / "ghost.mp3")
        mock_model.transcribe.assert_not_called()

    def test_passes_string_path_to_whisper(
        self, recogniser: WhisperSpeechRecogniser, mock_model: MagicMock, tmp_path: Path
    ) -> None:
        """Whisper expects a str path, not a Path object."""
        audio = tmp_path / "audio.mp3"
        audio.write_bytes(b"fake")
        mock_model.transcribe.return_value = _mock_whisper_result("hello", [])
        recogniser.recognise(audio)
        mock_model.transcribe.assert_called_once_with(str(audio))


# ---------------------------------------------------------------------------
# Transcript and confidence
# ---------------------------------------------------------------------------

class TestTranscriptResult:
    def test_returns_transcript_result_instance(
        self, recogniser: WhisperSpeechRecogniser, mock_model: MagicMock, tmp_path: Path
    ) -> None:
        audio = tmp_path / "audio.mp3"
        audio.write_bytes(b"fake")
        mock_model.transcribe.return_value = _mock_whisper_result(" hello ", [])
        result = recogniser.recognise(audio)
        assert isinstance(result, TranscriptResult)

    def test_text_is_stripped(
        self, recogniser: WhisperSpeechRecogniser, mock_model: MagicMock, tmp_path: Path
    ) -> None:
        audio = tmp_path / "audio.mp3"
        audio.write_bytes(b"fake")
        mock_model.transcribe.return_value = _mock_whisper_result("  hello world  ", [])
        result = recogniser.recognise(audio)
        assert result.text == "hello world"

    def test_confidence_zero_when_no_segments(
        self, recogniser: WhisperSpeechRecogniser, mock_model: MagicMock, tmp_path: Path
    ) -> None:
        audio = tmp_path / "audio.mp3"
        audio.write_bytes(b"fake")
        mock_model.transcribe.return_value = _mock_whisper_result("", [])
        result = recogniser.recognise(audio)
        assert result.confidence == 0.0

    def test_confidence_matches_mean_logprob(
        self, recogniser: WhisperSpeechRecogniser, mock_model: MagicMock, tmp_path: Path
    ) -> None:
        audio = tmp_path / "audio.mp3"
        audio.write_bytes(b"fake")
        segments = _make_segments(-0.3, -0.7)
        mock_model.transcribe.return_value = _mock_whisper_result("test", segments)
        result = recogniser.recognise(audio)
        expected = math.exp((-0.3 + -0.7) / 2)
        assert result.confidence == pytest.approx(expected)

    def test_confidence_in_valid_range(
        self, recogniser: WhisperSpeechRecogniser, mock_model: MagicMock, tmp_path: Path
    ) -> None:
        audio = tmp_path / "audio.mp3"
        audio.write_bytes(b"fake")
        mock_model.transcribe.return_value = _mock_whisper_result(
            "text", _make_segments(-0.1, -0.9, -0.5)
        )
        result = recogniser.recognise(audio)
        assert 0.0 <= result.confidence <= 1.0


# ---------------------------------------------------------------------------
# Integration test — real audio file
# ---------------------------------------------------------------------------

@pytest.mark.integration
@pytest.mark.skipif(not _LIVE_AUDIO.exists(), reason="Live audio file not found in audio_cache/")
class TestWhisperIntegration:
    """Runs Whisper against the real TTS-generated audio file.

    Requires the Whisper 'base' model to be downloaded and the file
    audio_cache/cf006606aa876074.mp3 to exist (generated by scripts/test_tts_live.py).
    """

    @pytest.fixture(scope="class")
    def result(self) -> TranscriptResult:
        sr = WhisperSpeechRecogniser()
        return sr.recognise(_LIVE_AUDIO)

    def test_transcript_contains_key_words(self, result: TranscriptResult) -> None:
        """The transcript should contain the main words from the synthesised text.

        'love' is used as the stem to accommodate Whisper transcribing
        'loved' as 'love' — both are correct recognitions of the audio.
        """
        transcript = result.text.lower()
        for word in ("god", "love", "world"):
            assert word in transcript, f"Expected '{word}' in transcript: {result.text!r}"

    def test_confidence_is_reasonable(self, result: TranscriptResult) -> None:
        """A clean TTS audio file should yield a confidence above 0.5."""
        assert result.confidence > 0.5, f"Low confidence: {result.confidence}"

    def test_result_is_transcript_result(self, result: TranscriptResult) -> None:
        assert isinstance(result, TranscriptResult)

    def test_text_is_non_empty(self, result: TranscriptResult) -> None:
        assert len(result.text) > 0
